services:
  api:  # Dieser Key muss statisch bleiben
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}:latest  # Variable hier moglich
    container_name: ${PROJECT_NAME} # Variable hier moglich
    restart: "no"
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env